// Compiles src/styles/tokens.json to src/styles/tokens.css, the same way the design system's
// build-tokens.py does, with one change: the dark theme is written twice, under
// `prefers-color-scheme` guarded by `:root:not([data-theme="light"])` and under
// `:root[data-theme="dark"]`, which is the attribute Starlight sets.
//
// tokens.json is a copy of design-system/tokens.json in the private sluiceway/company repo.
// To update it, copy that file over src/styles/tokens.json and run `bun run tokens`.
// `bun run tokens --check` fails when tokens.css does not match tokens.json.

import { readFileSync, writeFileSync } from "node:fs";

type Themed = string | Record<string, string>;
interface Token {
  name: string;
  value: Themed;
}
interface TypeStyle {
  name: string;
  family?: string;
  fontSize: string;
  lineHeight: string;
  fontWeight: number;
  letterSpacing?: string;
}
interface Tokens {
  color: { themes: { id: string }[]; tokens: Token[] };
  shadow?: { tokens: Token[] };
  spacing?: { tokens: Token[] };
  radius?: { tokens: Token[] };
  border?: { tokens: Token[] };
  tilt?: { tokens: Token[] };
  type: {
    families: Record<string, string>;
    groups: { family?: string; styles: TypeStyle[] }[];
  };
}

const SOURCE = "src/styles/tokens.json";
const OUTPUT = "src/styles/tokens.css";

function valueFor(token: Token, theme: string, first: string): string | undefined {
  const v = token.value;
  if (typeof v === "string") return theme === first ? v : undefined;
  return v[theme] ?? (theme !== first ? undefined : v[first]);
}

function resolve(v: string): string {
  const ref = /^\{([^}]+)\}$/.exec(v);
  return ref ? `var(--${ref[1]})` : v;
}

function block(selector: string, decls: string[], indent = ""): string {
  const body = decls.map((d) => `${indent}  ${d}`).join("\n");
  return `${indent}${selector} {\n${body}\n${indent}}`;
}

export function compile(t: Tokens): string {
  const themes = t.color.themes.map((th) => th.id);
  const first = themes[0];
  if (first === undefined) throw new Error("tokens.json has no colour themes");

  const themed = (theme: string): string[] => {
    const decls: string[] = [];
    for (const tok of t.color.tokens) {
      const v = valueFor(tok, theme, first);
      if (v) decls.push(`--${tok.name}: ${resolve(v)};`);
    }
    for (const tok of t.shadow?.tokens ?? []) {
      const v = valueFor(tok, theme, first);
      if (v) decls.push(`--${tok.name}: ${v};`);
    }
    return decls;
  };

  const out: string[] = [
    "/* Generated by scripts/build-tokens.ts from src/styles/tokens.json. Do not edit by hand.",
    "   tokens.json is a copy of design-system/tokens.json in sluiceway/company. */",
    "",
    block(":root", themed(first)),
  ];

  for (const theme of themes.slice(1)) {
    const decls = themed(theme);
    out.push(
      "",
      `@media (prefers-color-scheme: ${theme}) {`,
      block(`:root:not([data-theme="${first}"])`, decls, "  "),
      "}",
      "",
      block(`:root[data-theme="${theme}"]`, decls),
    );
  }

  const fixed: string[] = [];
  for (const family of ["spacing", "radius", "border", "tilt"] as const) {
    for (const tok of t[family]?.tokens ?? []) fixed.push(`--${tok.name}: ${tok.value};`);
  }
  for (const [k, v] of Object.entries(t.type.families)) fixed.push(`--font-${k}: ${v};`);
  out.push("", block(":root", fixed));

  // Type styles become `.sw-type-<name>`: Starlight already owns `.hero` and `.title`.
  for (const group of t.type.groups) {
    for (const s of group.styles) {
      const decls = [
        `font-family: var(--font-${s.family ?? group.family ?? "sans"});`,
        `font-size: ${s.fontSize};`,
        `line-height: ${s.lineHeight};`,
        `font-weight: ${s.fontWeight};`,
      ];
      if (s.letterSpacing) decls.push(`letter-spacing: ${s.letterSpacing};`);
      out.push("", block(`.sw-type-${s.name}`, decls));
    }
  }

  return `${out.join("\n")}\n`;
}

if (import.meta.main) {
  const css = compile(JSON.parse(readFileSync(SOURCE, "utf8")) as Tokens);
  if (process.argv.includes("--check")) {
    if (readFileSync(OUTPUT, "utf8") !== css) {
      console.error(`${OUTPUT} does not match ${SOURCE}. Run \`bun run tokens\` and commit.`);
      process.exit(1);
    }
    console.log(`${OUTPUT} is up to date.`);
  } else {
    writeFileSync(OUTPUT, css);
    console.log(`Wrote ${OUTPUT} (${css.length} bytes).`);
  }
}
